Require mysql_client_package for keystone_db_sync in cloud::identity
At the moment it is not possible to run the task keystone_db_sync in
the class cloud::identity on a new node because the mysql binary is
missing.

Error: /Stage[main]/Cloud::Identity/Exec[keystone_db_sync]: Could not evaluate:
Could not find command '/usr/bin/mysql'

Change-Id: I38fcd3e4b4714037098fa191ec2278624fcf4635