Swift: disable ceilometer middleware
Because of SElinux trouble:
IOError: [Errno 13] Permission denied: /var/log/ceilometer/swift-proxy-server.log'

We can't have SElinux + Swift with Ceilometer middleware working now.
Until it's figured & fixed, let's disable it.

Change-Id: I61a57076e59ed119b52330fdfd709e53bc356b30