Required MySQL server package for changing owner of MySQL dirs
Use of cloud::database::sql::mysql is not possible on CentOS 7 because
of the following issue:

Error: Could not set 'directory' on ensure: Could not find user mysql at
353:/etc/puppet/modules/cloud/manifests/database/sql/mysql.pp

Requiring the package $mysql_server_package_name before changing
the owner of the MySQL dirs solves this issue.

Change-Id: Ia39c9aaa2ec253dfc5ebaad776e2ae915b3f68a5