Revert "enable ceilometer & staticweb middlewares"
This reverts commit 9f41ace5fb85698e999a7176a98efb4e120237df.

  LookupError: No section 'staticweb' (prefixed by 'app' or 'application'
    or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in
    config /etc/swift/proxy-server.conf

  LookupError: No section 'ceilometer' (prefixed by 'app' or 'application'
    or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in
    config /etc/swift/proxy-server.conf