Revert "loadbalancer: Allow user to bind multiple public/private ips"
Error to compile the catalog:
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: member(): Requires array to work with at
/etc/puppet/modules/cloud/manifests/loadbalancer.pp:262 on node
os-ci-test10
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

The patch is going to be reverted and redone by spredzy.
This reverts commit 78397ab2406c66f76614b91672e5b2320f6cdfab.

Signed-off-by: Emilien Macchi <emilien.macchi@enovance.com>