Require that the service xinetd should be running
```
Error: /Stage[main]/Cloud::Database::Sql/Exec[reload_xinetd]: Failed to call refresh: /usr/bin/pkill -F /var/run/xinetd.pid --signal HUP returned 1 instead of one of [0]
Error: /Stage[main]/Cloud::Database::Sql/Exec[reload_xinetd]: /usr/bin/pkill -F /var/run/xinetd.pid --signal HUP returned 1 instead of one of [0]
```

close #91